### PR TITLE
allow to force site client when we are in admin

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This PR is for allowing JRoute to make links from admin to site and vice-versa.
This is a current problem especially if you are try to make SEF links from the backend to the frontend.
##### Test 1: Links from admin to site

Add to isis index.php file...

``` php
$app = JFactory::getApplication();
$app->enqueueMessage('1. Admin to Admin: ' . JRoute::_('index.php'), 'notice');
$app->enqueueMessage('2. Admin to Admin: ' . JRoute::_('index.php?option=com_content'), 'notice');
$app->enqueueMessage('3. Admin to Site: ' . JRoute::_('index.php?option=com_content', true, null, 'site'), 'notice');
$app->enqueueMessage('4. Admin to Site (MutilLanguage 1): ' . JRoute::_('index.php?option=com_content&lang=pt', true, null, 'site'), 'notice');
$app->enqueueMessage('5. Admin to Site (MutilLanguage 2): ' . JRoute::_('index.php?option=com_users&lang=en', true, null, 'site'), 'notice');

```

Result:
image

You should test also other URL.
##### Test 2: Links from site to admin

Add to protostar index.php file...

``` php
$app = JFactory::getApplication();
$app->enqueueMessage('1. Site to Site: ' . JRoute::_('index.php'), 'notice');
$app->enqueueMessage('2. Site to Site: ' . JRoute::_('index.php?option=com_content'), 'notice');
$app->enqueueMessage('3. Site to Admin: ' . JRoute::_('index.php?option=com_content', true, null, 'administrator'), 'notice');
```

Result:
image

You should test also other URL.
Try with the several variation of SEF/non-SEF,  with or without URL rewritting,  with or without multilanguage.
##### Test 3: Code review

Do a code review.
##### Test 4: Current URLs

Check if current URL generated by JRouter are exactly the same.
Problably the best is to leave the patch applied for some time, while you do other things and check there are no problems with the current URLs.
#### Observations

Thanks to @mbabker, @ggppdk and @infograf768 for helping out with this one.

Also, to make sure that are no unintended consequences, it would be good if this can be also reviewed from someone that understand the Router better than i do.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@mbabker how about this?

This should allow making sites from site to administrator and from administrator to site and using JRoute.

Could you code review to see if i did some thing i'm not supposed (or that is not B/C)?

I would really apreciate it. Thanks.

**Comment by mbabker** [comment]
Should work.

**Comment by andrepereiradasilva** [comment]
thanks for the review!

**Comment by andrepereiradasilva** [comment]
humm just noticed from admin to site it doesn't work properly in multilanguagee (it seems is nto reading the sef lang)

**Comment by ggppdk** [comment]
I was trying to create SEF links from **backend**, 

```
JFactory::$application = JApplication::getInstance('site');
// Create SEF link
JFactory::$application = ... restore previous value
```

but had to remove it because it was breaking AJAX ACL saving (strange but i did not look it more)
(now i am using non-SEF urls)

i ll test this PR,  question why is this PR at repository:
https://github.com/andrepereiradasilva/joomla-cms/

about language i am including language in the URLs, to make sure that correct article is shown

**Comment by andrepereiradasilva** [comment]
@ggppdk this is at my repository because i didn't find a solution for the language issue ...

> humm just noticed from admin to site it doesn't work properly in multilanguagee (it seems is nto reading the sef lang)

**Comment by infograf768** [comment]
I confirm the multilang issue

**Comment by andrepereiradasilva** [comment]
yes, something is strange with multilangue routing ....

**Comment by andrepereiradasilva** [comment]
routing is not my beach...
does anyone understand why the language plugin does not add the language routes when called from administrator?

It seems the system language filter plugin events are not executed in this case.

**Comment by mbabker** [comment]
The languagecode and languagefilter plugins have checks against `$app->isSite()`.  Beyond that I've got nothing.

**Comment by andrepereiradasilva** [comment]
thanks to @mbabker i think i may found the main problems (see https://github.com/andrepereiradasilva/joomla-cms/pull/36/commits/0faa289b83e3548182551a75c7754fbb3b2885ca?w=1)

There are two problems:
1. What @mbabker said
2. The language filter plugin is attaching routing events to router according to the user app (site or admin), in case of the user is in admin app it's loading JRouterAdministrator (this routing events should be loaded on JRouterSite). to solve this i force it to always use JRouterSite.

Now it generates the correct URL's for the tests i made in multilanguage. This is not a full test and there still may be issues, but i think we are getting near it.

**Comment by andrepereiradasilva** [comment]
@infograf768 all seems ok for you?

**Comment by andrepereiradasilva** [comment]
@ggppdk can you please try and give feedback?

**Comment by ggppdk** [comment]
I ll have time to test tomorrow morning , will do, thanks

**Comment by infograf768** [comment]
Will test tomorrow to make sure it does not break anything on the Site side.

**Comment by infograf768** [comment]
Let's not forget the correct type of links that should be used in back-end:
`<a href="index.php?option=com_content&amp;view=article&amp;id=213&amp;catid=10&amp;lang=en-GB&amp;Itemid=101" hreflang="en">some article title</a>`
We can forget the hreflang if that link is just to get a preview.

**Comment by andrepereiradasilva** [comment]
> Let's not forget the correct type of links that should be used in back-end:
> <a href="index.php?option=com_content&amp;view=article&amp;id=213&amp;catid=10&amp;lang=en-GB&amp;Itemid=101" hreflang="en">some article title</a>
> We can forget the hreflang if that link is just to get a preview.

JRoute::_() just creates the URL, nothing more

**Comment by ggppdk** [comment]
Tested by adding preview links to Joomla article manager listing
(which many users would like to have ...)

and did same with my component too, **routing work for both** 

Tested both with language associated records
- no sef
- sef
- sef with URL rewritting

@andrepereiradasilva 
Can you rebase this to latest staging ?

**Comment by andrepereiradasilva** [comment]
nice! thanks. 

> Can you rebase this to latest staging ?

will try to do it tomorrow.

@infograf768 can you please check too when you have time?

**Comment by andrepereiradasilva** [comment]
PR created https://github.com/joomla/joomla-cms/pull/11060

**Pull request closed without merging**
