### PR TITLE
pdo mysql strict mode - installa with languages enabled + content

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #11763 .

fix for  #11763 pdo mysql strict mode - install with languages enabled + content

please test and do the same fix on mssql and when update

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
i already made a change in the PR yesterday, did you check the code diff. did you test the latest version.
Also i don't agree in removing the not null, all the other databases have it.

**Comment by alikon** [comment]
i followed this path
- downloaded the latest staging 
- installed with mysql no pdo
- installed the com_patchter
- applyed PR #11763 with the last changes (as  it is now)
- dropped all tables in the database
- deleted the configuration.php
- added the strict mode to pdomysql.php at line 155

``` php
//$this->connection->query("SET @@SESSION.sql_mode = '';");
$this->connection->query("SET @@SESSION.sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';");
```
- double checked that all changes in the PR #11763 are correctly in place
- started a new installation with mysql pdo strict mode as a database
- select the no data for basic multiligual install
- double check that PR are corretclty  applyied as db schema on chenged tables checked with phpmyadmin
- click on extra step install languages
-  got the sql error

strictpdo

p.s. 
PDO sould be considered as a different DB .... what is valid for other's DB is not valid with PDO

i've uploaded a "dirty" video on youtube https://youtu.be/BNXSUJqJVSs with a step by step of the process i've followed hope this may help more

**Comment by andrepereiradasilva** [comment]
@alikon i just saw your video yet again and discovered you get the error BEFORE installating any language. Minute 7:25 to end of your video

You get the error afer clicking "installa languages" to go to the language select.

This is different from the error i solved: the error when you selected a language and press install.

**Comment by alikon** [comment]
see #72

**Pull request closed without merging**
