### PR TITLE
Associations edit

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue.
### Summary of Changes

In a multilingual install with associations, when you change the item language the associations will be wrong.

This PR makes the associations be reseted on language changes.
Also:
- allows to add associations on item create (that was disabled because of this problem)
- allows to change the language on item edit (that was disabled because of this problem)
### Testing Instructions
1. Use latest 3.7.x, multilingual with associations enabled
2. Apply patch 
3. For articles, categories, contacts, menus and newsfeeds check:
4. Adding associations when creating an item (try changing the languages)
5. Changing languages when editng an item
### Documentation Changes Required

None.
### Notes

I introduced here two new methods: `JLanguageHelper::getContentLanguages` (get the content languages from `#__languages`) and `JLanguageHelper::getInstalledLanguages` (get the installed languages from `#__extensions` table).

Why this two new methods? 
- because `JLanguageHelper::getLanguages()` always return the published languages ...
- JLanguageHelper::getLanguages() **does not check if the content languages are installed** which, of course, can, and will, lead to errors if you, for instance, unintall a language package.
- because `JLanguageHelper::getLanguages()` is not IMHO semantic correct: get what languages? installed? content languages?
- among more things (like performance)

This two methods will allow to do all languages related stuff across the core in the future (replacing several hardcoded queries, etc).

### CODE REVIEW

**Comment by infograf768** [comment]
It does not work for categories here. The category edited language is proposed in associations. I am editing here a French tagged category
screen shot 2016-10-06 at 16 24 22

Yes, we do need a Notice that changing the language and saving will delete existing associations.

Concerning unpublished content languages, we can already associate items tagged to the unpublished content language to the published content languages ones.
But we can't, when editing an item tagged to a published content language, associate to an item tagged to an unpublished CL. That is not logical.

We should indeed be able to prepare associations that would ONLY display when the language is published. This is the case already btw when setting Global com_content Options to Show Associations

Which makes me think that getting into an article the link to an article or a contact or a menu item tagged to an unpublished content language through the xtd buttons may create issues.
The link is then modified to use the sef of the language displayed... Quite bad.

**Comment by andrepereiradasilva** [comment]
> But we can't, when editing an item tagged to a published content language, associate to an item tagged to an unpublished CL. That is not logical.
> We should indeed be able to prepare associations that would ONLY display when the language is published. This is the case already btw when setting Global com_content Options to Show Associations

yes, that was what i was talking about.

> Which makes me think that getting into an article the link to an article or a contact or a menu item tagged to an unpublished content language through the xtd buttons may create issues.
> The link is then modified to use the sef of the language displayed... Quite bad.

Will give 404, but that's a user msitake right. I see no problem in this

**Comment by andrepereiradasilva** [comment]
ok we have a warning message and just when there are associations (if the associatiosn fields are empty there is no message when changing language)

also the categories issue is solved (somehow the categories label id field id different than the others ...... ! )

so the only think left is the unpublished langauges that i will do tonight (i hope)

and, of course, lots of tests

**Comment by andrepereiradasilva** [comment]
ok all should be fine now
please test

**Comment by andrepereiradasilva** [comment]
please note also that i introduce here two new methods in `JLanguageHelper` that i have been working for long time: `getContentLanguages` and `getInstalledLanguages`

why? 
- because IMO `JLanguageHelper::getLanguages()` is not semantic correct: get what languages? installed? content languages?
- because `JLanguageHelper::getLanguages()` always return the published languages ...
- because `JLanguageHelper::getLanguages()` always order the content languages in the same way ...
- JLanguageHelper::getLanguages() **does not check if the content languages are installed** which, of course, can, and will, lead to errors if you, for instance, unintall a language package.
- among more things
- This two methods will allow to do all languages related stuff across the core in the future (replacing several hardcoded queries etc) across the core and with static caching

**Comment by infograf768** [comment]
Categories now OK. 👍 

> JLanguageHelper::getLanguages() does not check if the content languages are installed which, of course, can, and will, lead to errors if you, for instance, uninstall a language package.

Not sure I get you here: the multilang status shows possible errors.
screen shot 2016-10-07 at 12 54 38

I am personnaly, as you know well, not very much in favour of PRs that do not only solve the issue at stake but also refactor stuff... here it's quite a major refactoring. Did not go over all that stuff.

Note: I have tested the following:
An item has associations. I change its language. I get the warning. 
Let's say I close the warning.
If I do not close but change back the language to its original value, I do not get the warning again and I have to redo the associations or lose them on save. Anything we can do for that?

**Comment by andrepereiradasilva** [comment]
> Not sure I get you here: the multilang status shows possible errors.

This is not relevant for this case.

> I am personnaly, as you know well, not very much in favour of PRs that do not only solve the issue at stake but also refactor stuff... here it's quite a major refactoring. Did not go over all that stuff.

I know and i'm not also, but each time i try to do some refactoring almost nobody test or comment it because it's too techniclliy (especcially language stuff that is almost you and i) and i end up closing it after a few months ... but of course that isn't the motive ... just complaining!  😉 

The real thing is without this methods i have to do new sql queries but without the published =1, because getLanguages ALWAYS check the published. Basdicly a lot of duplicated code that is not needed IMO!

Anyway this DOES NOT CHANGE anything in the current CMS behaviour. they are only used in this situation for now.

> If I do not close but change back the language to its original value, I do not get the warning again and I have to redo the associations or lose them on save. Anything we can do for that?

doesn't seem anything that i can do i'm afraid. i can't recover the previous associations, if's that you are asking.

**Comment by infograf768** [comment]
then let's go with it and see if we can get this in for 370

**Pull request closed without merging**
