### PR TITLE
fix for #11763 with php 5.5

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #11763 .

in this way i was able to install language on installation and after from backend
### Summary of Changes

set a default when needed
### Testing Instructions

php < 7.x
mysql strict mode

### CODE REVIEW

**Comment by alikon** [comment]
conf2

languages
languagesi

when you have time can you test on your configuration both ways on install and after....

**Comment by andrepereiradasilva** [comment]
i understand the fix, but setting it to a one space string can have other consequences IMHO

**Comment by alikon** [comment]
Should be the same as NOT NULL WITH DEFAULT ' '

On 30 Aug 2016 12:07 pm, "andrepereiradasilva" notifications@github.com
wrote:

i understand the fix, but setting it to a one space string can have other
consequences IMHO

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/andrepereiradasilva/joomla-cms/pull/72#issuecomment-243394053,
or mute the thread

**Comment by andrepereiradasilva** [comment]
`''`is different than `' '`

**Comment by alikon** [comment]
sorry, you are right fixed now
p,s
i should not code on train early in the morning ;)

**Pull request merged**
