### PR TITLE
extensions update fix for #11763

### PR DESCRIPTION
**Pull request by alikon**
extensions update fix for #11763

i've tested installing/unistalling com_patchtester and pkg-weblinks (3.5.0) successfully, then
i've tested installing pkg-weblinks (3.4.0) successfully and  then desicoverd the upgrade and upgrading to 3.5.0 successfully

please review and test carefully cause i've again coded on train ;)

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
If you have the database with a column set as default with `''` why do we need to force the value as `''`?? This doesn't makes sense to me. That exactly why the DEFAULT exists in database systems right?

**Comment by alikon** [comment]
for the same reason as for #72

**Comment by andrepereiradasilva** [comment]
Yes, i know, but you are a database expert, does this makes sense to you?

I have the feeling we are masking some other problem in your particular installation with this.

**Comment by alikon** [comment]
yes make sense for me, cause i think we are going around some php <7.x  driver issues like the others already fixed before, consider  that php 7.x is not  largely adopted till now...unfortunately

**Comment by andrepereiradasilva** [comment]
> If you update a column that has been declared NOT NULL by setting to NULL, an error occurs if strict SQL mode is enabled; otherwise, the column is set to the implicit default value for the column data type and the warning count is incremented. The implicit default value is 0 for numeric types, the empty string ('') for string types, and the “zero” value for date and time types. See Section 11.6, “Data Type Default Values”.

Source: http://dev.mysql.com/doc/refman/5.5/en/update.html

> In strict mode, an error occurs if any column doesn't have a default value. Otherwise, MySQL uses the implicit default value for any column that does not have an explicitly defined default.

Source: http://dev.mysql.com/doc/refman/5.5/en/insert.html

**Comment by andrepereiradasilva** [comment]
ok, so for what i understand, you think the problem is the pdo php 5.6 or less driver that is not using the DEFAULT value when it exists if pdo mysql set to strict mode?

the problem i see if we merge this we need to test all the update system, including joomla update ...

**Comment by alikon** [comment]
test before merge of course.... i've already done my non regression test with mysqli and with postgres
with the same php version, i don't have php 7 .... please test on your environment with php > 7 and report back if any issues arise

**Comment by andrepereiradasilva** [comment]
ok will try to test for no regression. Since i don't have issues with this at all.

**Comment by andrepereiradasilva** [comment]
@alikon the store is being done here https://github.com/andrepereiradasilva/joomla-cms/blob/staging/libraries/joomla/table/table.php#L764 and then here https://github.com/andrepereiradasilva/joomla-cms/blob/staging/libraries/joomla/table/table.php#L793

postgresql and sqlsrv have overloaded this `insertObject` JDatabaseDriver method, but pdomysql didn't.
- postgresql: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/postgresql.php#L1116
- sqlsrv: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/sqlsrv.php#L478
- fallback (all others): https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver.php#L1375

i really suspect there is some bug there for pdomysql and not in the PHP driver.

did you test making a direct sql insert in the same table in pdo mysql strict mode? i mean, with no data in the data field with your php 5.5 driver?

**Comment by alikon** [comment]
it can be as well...not yet but surely i'll do it,,,

**Pull request closed without merging**
