### PR TITLE
rebase 3.5.1-2016-03-25.sql

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/9579 (rebase)

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
i will have to change the file name as it will not go fot 3.5.2 and not to that date so will reject.
But thanks anyway.

**Comment by wojsmol** [comment]
@andrepereiradasilva So 3.5.2 plus the current date? Already working on it. Give me a few minutes :smile:

**Comment by andrepereiradasilva** [comment]
but for all drivers

**Comment by wojsmol** [comment]
ok, no problem

**Comment by wojsmol** [comment]
@andrepereiradasilva See #26

**Pull request closed without merging**
